### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by NickLee380** [caiya/vuejs-admin#5]
输入测试账号，然后页面上出现下面错误，console上没有错误信息。
Cannot read property 'data' of undefined

**Comment by caiya** [comment]
服务端启动了吗，没有启动的话可以看下vuejs-admin-server

**Comment by caiya** [comment]
@NickLee380 已经修改了，请拉去最新的客户端和服务端代码

**Comment by ma1953** [comment]
，我连接自己的Mqtt服务器，设备监控的曲线收不到MQTT.fx发来的数据

**Comment by caiya** [comment]
@ma1953 可以检查下mqtt的topic具体对不对
